### ISSUE TITLE
Problem using imported saves that predate Welcome Amiibo

### ISSUE THREAD

**Issue by camperdave** [dragos240/TownManager#1]
So, if you take a save exported from another tool (in this case, JKSM) and manually create a town folder containing all the old-version files (ie: garden.dat), when you launch it'll take you into the Main save's town if that save has been updated to garden_plus. I haven't dove in deep enough to really confirm this, but looking at `prepare_to_launch` in launcher.c, I don't see any code that would _delete_ the garden_plus.dat file - is it possible this issue is caused by that upgraded file still sticking around?

While this is a niche issue, the way that TownManager auto-saves when you re-open the tool seems to foul up the backup when you re-open it in this state, so I wanted to report the bug. Please let me know if there's any more info I can provide.

**Comment by dragos240** [comment]
Well a fix for that would be for me to update prepare_to_launch so that it deletes all save files on the game card. That would provide a more clean save update as well. Let me fix that and I'll provide a link to the commit this is fixed in. I'll also make a bugfix release.

**Comment by camperdave** [comment]
Sounds like a plan to me. Just to add a little detail, I am playing on the eShop version, so I can't promise it actually exists as a bug on the cartridge side, if there are any differences.

**Comment by dragos240** [comment]
Another question, what does this bug actually _break_ for you? Did you delete the update files and trying to play the old version of the game?

**Comment by camperdave** [comment]
It arose when moving a save file from one 3DS without the update to another which had the update.

**Comment by dragos240** [comment]
Heh. I was going to say "this was fixed in commit 3fc671f" but it looks like github does that automatically. Neat. Anyway, [Here's the latest release](https://github.com/dragos240/TownManager/releases/tag/v1.1.0) that fixes the issue. Also added "Clone" and "Rename" features.
