### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by LizNuzz** [dragos240/TownManager#6]
Hi!

Your work sounds great, but I feel a little stupid. I just really cannot figure out how to install the TownManager. I downloaded TownManager-v1.2.1.zip and put the unzipped folder on my SD card for my 3DS. I tried both the main directory and the "Nintendo 3ds" directory.
When I put the SD card back into the 3DS and start the system, there is no app for me to open. What do I have to do differently?

My 3DS has the newest updates as of today (June 21st 2019). I own a hard copy version of acnl (opposed to a download version of the game).

I'm sorry I have to ask this very basic question, but I can't seem to find and answer online so far.

**Comment by dragos240** [comment]
No worries, I'll help.

TownManager has two different forms. The 3dsx form and the cia one. The 3dsx one requires the homebrew menu. The cia one requires a homebrewed system with boot9strap. If you've already installed boot9strap, you can use FBI to install the cia onto your system. I do suggest installing boot9strap as there are no risks to your console and it makes installing homebrew much easier.

You can follow [this guide](https://3ds.hacks.guide/) to install boot9strap. Do NOT use the youtube tutorials as they're outdated and could potentially give you wrong information.

I hope this helps! Good luck! :)

**Comment by LizNuzz** [comment]
Thank you for the quick feedback! I'll try that

**Comment by dragos240** [comment]
No further questions asked. Closing.
