### ISSUE TITLE
"Error! Could not find a copy of AC:NL on this device!" (get_titleid failed) | IS ACNL:WA compatible? 

### ISSUE THREAD

**Issue by roobswonderland** [dragos240/TownManager#8]
hello! i wanted to preface this by saying i'm relatively new to the 3ds modding scene and i may be unfamiliar with some terms. if i ask, it's not to be rude or condescending, just me being a little silly :)

i recently got my copy of Animal Crossing New Leaf Welcome Amiibo on my 3ds! however, whenever I try to use this program, it keeps giving me this error:
"Error! Could not find a copy of AC:NL on this device!"
"get_titleid failed"

i'm not exactly sure what i'm doing wrong :(. i'm sorry if this is reviving a long-dead project, but i would really like to not have to decrypt and re-encrypt my ACNL:WA just to make some edits to my save.

thank you in advance, hope you have a great day!!

**Comment by dragos240** [comment]
Hey, I haven't worked on this project for years and years. It's not compatible with the update I don't think.

**Comment by roobswonderland** [comment]
aw jeez, my bad. well thank you for the lightning fast response! 
good luck on your other endeavors !!!! :D
